### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by applike-ss**
I added the already supplied favicon to the index page. 

This way the tab can be found easier if you haven lots of open tabs.

At the same time it will remove favicon.ico requests from the network monitor, which will always be answered with 404s.

### CODE REVIEW

**Review by rodrigo-brito — CHANGES_REQUESTED** [review]
Hi @applike-ss, thank you for the contribution.
But, we have a fivicon
image
The favicon is in default path: https://go-city.github.io/favicon.ico

**Comment by rodrigo-brito** [comment]
If you prefer, you can update the `<link rel="icon"` with the URL (https://go-city.github.io/favicon.ico), but it is not necessary

**Comment by applike-ss** [comment]
Would you mind including that in the repo as well? That way everyone who hosts his/her own gocity locally can have the favicon too.

**Comment by rodrigo-brito** [comment]
Shure, but the url is not correct, as described bellow.

Correct url: `/favicon.ico`

**Pull request closed without merging**
